Tragon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('TragonBall.urls')),
    path('carro/', include('carro.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

TragonBall/urls.py
from django.urls import path
from . import views

app_name = "TragonBall"

urlpatterns = [
    path('', views.inicio, name="inicio"),
    path('registrarse', views.registroCliente, name="reg"),
    path('iniciarsesion', views.paginaLogin, name='paginaLogin'),
    path('cerrarSesion', views.cerrarSesion, name='cerrarSesion'),
    path('contacto/', views.contacto, name="contacto"),
    path('nosotros', views.nosotros, name="nosotros"),
    path('tiposPago', views.tiposPago, name="tiposPago"),
    path('delivery', views.delivery, name="delivery"),
    path('producto', views.producto, name="producto"),
    path('promocion', views.promocion, name="promocion"),
    path('carro', views.carro, name="carro"),
    path('comprar', views.comprar, name="comprar"),
     path('comprahecha', views.comprahecha, name="comprahecha"),
    #path('sucess/', views.sucess, name="sucess"),
    #path('mycart/', views.simple_checkout, name="simple"),
    
]

carro/urls.py
from django.urls import path
from . import views

app_name="carro"

urlpatterns = [
    path('agregar/<int:producto_id>/', views.agregar_producto, name="agregar"),
    path('eliminar/<int:producto_id>/', views.eliminar_producto, name="eliminar"),
    path('restar/<int:producto_id>/', views.restar_producto, name="restar"),
    path('limpiar/', views.limpiar_carro, name="limpiar"),
]

TragonBall/models.py
from django.db import models

class Categoria(models.Model):
    id_categoria = models.AutoField(db_column='ID_Categoria', primary_key=True)  # Field name made lowercase.
    descripcion_categoria = models.CharField(db_column='Descripcion_Categoria', max_length=100, blank=True, null=True)  # Field name made lowercase.
    estado_categoria = models.BooleanField(db_column='Estado_Categoria')  # Field name made lowercase.
    fecharegistrocategoria = models.DateField(db_column='FechaRegistroCategoria')  # Field name made lowercase.

    def __str__(self):
        return str(self.id_categoria)

class Cliente(models.Model):
    id_cliente = models.AutoField(db_column='ID_Cliente', primary_key=True)  # Field name made lowercase.
    nombre_cliente = models.CharField(db_column='Nombre_Cliente', max_length=50)  # Field name made lowercase.
    apellido_cliente = models.CharField(db_column='Apellido_Cliente', max_length=50)  # Field name made lowercase.
    correo_cliente = models.CharField(db_column='Correo_Cliente', max_length=50)  # Field name made lowercase.
    clave_cliente = models.CharField(db_column='Clave_Cliente', max_length=50)  # Field name made lowercase.
    telefono_cliente = models.CharField(db_column='Telefono_Cliente', max_length=50)  # Field name made lowercase.
    fecharegistrocliente = models.DateField(db_column='FechaRegistroCliente')  # Field name made lowercase.

class Compra(models.Model):
    id_compra = models.AutoField(db_column='ID_Compra', primary_key=True)  # Field name made lowercase.
    usuario_id_usuario = models.ForeignKey('Usuario', models.DO_NOTHING, db_column='USUARIO_ID_Usuario')  # Field name made lowercase.
    proveedor_id_proveedor = models.ForeignKey('Proveedor', models.DO_NOTHING, db_column='PROVEEDOR_ID_Proveedor')  # Field name made lowercase.
    tipodocumento_compra = models.CharField(db_column='TipoDocumento_Compra', max_length=50)  # Field name made lowercase.
    numerodocumento_compra = models.CharField(db_column='NumeroDocumento_Compra', max_length=50)  # Field name made lowercase.
    montototal_compra = models.IntegerField(db_column='MontoTotal_Compra')  # Field name made lowercase.
    fecharegistrocompra = models.DateField(db_column='FechaRegistroCompra')  # Field name made lowercase.

class DetalleCompra(models.Model):
    id_detallecompra = models.AutoField(db_column='ID_DetalleCompra', primary_key=True)  # Field name made lowercase.
    compra_id_compra = models.ForeignKey(Compra, models.DO_NOTHING, db_column='COMPRA_ID_Compra')  # Field name made lowercase.
    materia_prima_id_materiaprima = models.ForeignKey('MateriaPrima', models.DO_NOTHING, db_column='MATERIA_PRIMA_ID_MateriaPrima')  # Field name made lowercase.
    preciocompra = models.IntegerField(db_column='PrecioCompra')  # Field name made lowercase.
    precioventa = models.IntegerField(db_column='PrecioVenta')  # Field name made lowercase.
    cantidad_detallecompra = models.IntegerField(db_column='Cantidad_DetalleCompra')  # Field name made lowercase.
    montototal_detallecompra = models.IntegerField(db_column='MontoTotal_DetalleCompra')  # Field name made lowercase.
    fecharegistrodetallecompra = models.DateField(db_column='FechaRegistroDetalleCompra')  # Field name made lowercase.

class DetalleVenta(models.Model):
    id_detalleventa = models.AutoField(db_column='ID_DetalleVenta', primary_key=True)  # Field name made lowercase.
    venta_id_venta = models.ForeignKey('Venta', models.DO_NOTHING, db_column='VENTA_ID_Venta')  # Field name made lowercase.
    producto_elaborado_id_producto = models.ForeignKey('ProductoElaborado', models.DO_NOTHING, db_column='PRODUCTO_ELABORADO_ID_Producto')  # Field name made lowercase.
    precioventa = models.IntegerField(db_column='PrecioVenta')  # Field name made lowercase.
    cantidad_detalleventa = models.IntegerField(db_column='Cantidad_DetalleVenta')  # Field name made lowercase.
    subtotal_detalleventa = models.IntegerField(db_column='SubTotal_DetalleVenta')  # Field name made lowercase.
    fecharegistrodetalleventa = models.DateField(db_column='FechaRegistroDetalleVenta')  # Field name made lowercase.


class MateriaPrima(models.Model):
    id_materiaprima = models.AutoField(db_column='ID_MateriaPrima', primary_key=True)  # Field name made lowercase.
    categoria_id_categoria = models.ForeignKey(Categoria, models.DO_NOTHING, db_column='CATEGORIA_ID_Categoria')  # Field name made lowercase.
    codigo_materiaprima = models.CharField(db_column='Codigo_MateriaPrima', max_length=50, blank=True, null=True)  # Field name made lowercase.
    nombre_materiaprima = models.CharField(db_column='Nombre_MateriaPrima', max_length=50)  # Field name made lowercase.
    descripcion_materiaprima = models.CharField(db_column='Descripcion_MateriaPrima', max_length=100, blank=True, null=True)  # Field name made lowercase.
    stock_materiaprima = models.IntegerField(db_column='Stock_MateriaPrima')  # Field name made lowercase.
    preciocompra_materiaprima = models.IntegerField(db_column='PrecioCompra_MateriaPrima')  # Field name made lowercase.
    estado_materiaprima = models.BooleanField(db_column='Estado_MateriaPrima')  # Field name made lowercase.
    fecharegistro_materiaprima = models.DateField(db_column='FechaRegistro_MateriaPrima')  # Field name made lowercase.

class Permiso(models.Model):
    id_permiso = models.AutoField(db_column='ID_Permiso', primary_key=True)  # Field name made lowercase.
    id_rol = models.ForeignKey('Rol', models.DO_NOTHING, db_column='ID_Rol')  # Field name made lowercase.
    nombremenu = models.CharField(db_column='NombreMenu', max_length=100)  # Field name made lowercase.
    fecharegistropermiso = models.DateField(db_column='FechaRegistroPermiso')  # Field name made lowercase.

class ProductoElaborado(models.Model):
    id_producto = models.AutoField(db_column='ID_Producto', primary_key=True)  # Field name made lowercase.
    categoria_id_categoria = models.ForeignKey(Categoria, models.DO_NOTHING, db_column='CATEGORIA_ID_Categoria')  # Field name made lowercase.
    codigo_producto = models.CharField(db_column='Codigo_Producto', max_length=50, blank=True, null=True)  # Field name made lowercase.
    nombre_producto = models.CharField(db_column='Nombre_Producto', max_length=50)  # Field name made lowercase.
    descripcion_producto = models.CharField(db_column='Descripcion_Producto', max_length=200, blank=True, null=True)  # Field name made lowercase.
    stock_producto = models.IntegerField(db_column='Stock_Producto')  # Field name made lowercase.
    preciocompra = models.IntegerField(db_column='PrecioCompra')  # Field name made lowercase.
    precioventa = models.IntegerField(db_column='PrecioVenta')  # Field name made lowercase.
    estado_producto = models.BooleanField(db_column='Estado_Producto')  # Field name made lowercase.
    fecharegistroproducto = models.DateField(db_column='FechaRegistroProducto')  # Field name made lowercase.
    imagen = models.ImageField(upload_to='Imagen', blank=True, null=True)  # Field name made lowercase.

    def __str__(self):
        return self.id_producto
    

class Proveedor(models.Model):
    id_proveedor = models.AutoField(db_column='ID_Proveedor', primary_key=True)  # Field name made lowercase.
    rutempresa = models.CharField(db_column='RutEmpresa', max_length=50)  # Field name made lowercase.
    dvempresa = models.CharField(db_column='DVEmpresa', max_length=1)  # Field name made lowercase.
    razonsocial = models.CharField(db_column='RazonSocial', max_length=50)  # Field name made lowercase.
    correo = models.CharField(db_column='Correo', max_length=50)  # Field name made lowercase.
    telefono = models.CharField(db_column='Telefono', max_length=50)  # Field name made lowercase.
    fecharegistroproveedor = models.DateField(db_column='FechaRegistroProveedor')  # Field name made lowercase.

    def __str__(self):
        return self.rutempresa

class Rol(models.Model):
    id_rol = models.AutoField(db_column='ID_Rol', primary_key=True)  # Field name made lowercase.
    descripcion_rol = models.CharField(db_column='Descripcion_Rol', max_length=50)  # Field name made lowercase.
    fecharegistrorol = models.DateField(db_column='FechaRegistroRol')  # Field name made lowercase.
    id_permiso = models.IntegerField(db_column='ID_Permiso')  # Field name made lowercase.

class TipoPago(models.Model):
    id_pago = models.AutoField(db_column='ID_Pago', primary_key=True)  # Field name made lowercase.
    venta_id_venta = models.ForeignKey('Venta', models.DO_NOTHING, db_column='VENTA_ID_Venta')  # Field name made lowercase.
    metodopago = models.CharField(db_column='MetodoPago', max_length=50)  # Field name made lowercase.
    montopago = models.CharField(db_column='MontoPago', max_length=50)  # Field name made lowercase.
    fecharegistrotipopago = models.DateField(db_column='FechaRegistroTipoPago')  # Field name made lowercase.

class Usuario(models.Model):
    id_usuario = models.AutoField(db_column='ID_Usuario', primary_key=True)  # Field name made lowercase.
    rol_id_rol = models.ForeignKey(Rol, models.DO_NOTHING, db_column='ROL_ID_Rol')  # Field name made lowercase.
    rut_usuario = models.CharField(db_column='Rut_Usuario', max_length=50)  # Field name made lowercase.
    dv_usuario = models.CharField(db_column='DV_Usuario', max_length=1)  # Field name made lowercase.
    nombre_usuario = models.CharField(db_column='Nombre_Usuario', max_length=50)  # Field name made lowercase.
    apellidos_usuario = models.CharField(db_column='Apellidos_Usuario', max_length=50)  # Field name made lowercase.
    correo_usuario = models.CharField(db_column='Correo_Usuario', max_length=50)  # Field name made lowercase.
    clave_usuario = models.CharField(db_column='Clave_Usuario', max_length=50)  # Field name made lowercase.
    telefono_usuario = models.CharField(db_column='Telefono_Usuario', max_length=50)  # Field name made lowercase.

carro/models.py
from django.db import models

# Create your models here.

TragonBall/forms.py
from django import forms

class FormularioContacto(forms.Form):
    nombre = forms.CharField(label="Nombre", max_length=30, required=True, widget=forms.TextInput(attrs={'size': '43'}))
    correo = forms.EmailField(label="Correo", required=True, widget=forms.TextInput(attrs={'size':'43'}))
    mensaje = forms.CharField(label="Mensaje", max_length=1000, widget=forms.Textarea(attrs={'size': '42'}), required=True)

TragonBall/views.py
from email.message import EmailMessage
from django.shortcuts import render, redirect
from TragonBall.models import Cliente, ProductoElaborado, CompraPaypal
from django.contrib import messages
from .forms import FormularioContacto
from django.core.mail import EmailMessage
from django.contrib.auth import login, logout, authenticate
from django.http import HttpResponse, JsonResponse
from paypalcheckoutsdk.core import PayPalHttpClient, SandboxEnvironment
from paypalcheckoutsdk.orders import OrdersGetRequest, OrdersCaptureRequest
import sys, json
from carro.carro import Carro
#import json,random,requests

# Create your views here.

# Inicio
def inicio(request):
    return render(request, "inicio.html")


# Inicio
def comprahecha(request):
    return render(request, "comprahecha.html")
# Productos
def producto(request):
    producto = ProductoElaborado.objects.filter(categoria_id_categoria__in = [4,5,6,7])
    return render(request,'productos.html', {"producto":producto})

# Promociones
def promocion(request):
    promocion = ProductoElaborado.objects.filter(categoria_id_categoria='9')
    return render(request,'promocion.html', {"promocion":promocion})

#Registro
def registroCliente(request):
    if request.method=='POST':
        nombre=request.POST['nombre']
        apellido=request.POST['apellido']
        correo= request.POST['correo']
        clave=request.POST['password']
        telefono=request.POST['telefono']
        fecha=request.POST['fecha']
        Cliente(nombre_cliente=nombre, apellido_cliente=apellido, correo_cliente=correo, clave_cliente=clave, telefono_cliente=telefono, fecharegistrocliente=fecha).save()
        messages.success(request, request.POST['nombre'] +' se registro correctamente.')
        return render(request, 'registrarse.html')
    else:
        return render(request, 'registrarse.html')

#Login
def paginaLogin(request):
    if request.method=='POST':
        try:
            detalleC=Cliente.objects.get(correo_cliente=request.POST['correo'], clave_cliente=request.POST['password'])
            print("Cliente=", detalleC)
            request.session['Email']=detalleC.correo_cliente
            return render(request, 'inicio.html')
        except Cliente.DoesNotExist as e:
            messages.success(request, 'Email o contraseña incorrecta!')
    return render(request, 'iniciarsesion.html')

def cerrarSesion(request):
    try:
        del request.session['Email']
        
    except:
        return render(request, 'inicio.html')
    return render(request, 'inicio.html')


#Delivery
def delivery(request):
    return render(request, 'delivery.html')

#Nosotros
def nosotros(request):
    return render(request, 'nosotros.html')


# Contacto
def contacto(request):
    formulario=FormularioContacto()
    
    if request.method=="POST":
        formulario=FormularioContacto(data=request.POST)
        if formulario.is_valid():
            nombre=request.POST.get("nombre")
            correo=request.POST.get("correo")
            mensaje=request.POST.get("mensaje")

            correo=EmailMessage("Mensaje desde Tragón Ball Z",
            "El usuario con nombre {} y correo {}  envia lo siguiente:\n\n {}".format(nombre,correo,mensaje),
            "",["tragonballzpyme@gmail.com"],reply_to=[correo])

            try: 
                correo.send()
                messages.success(request, 'Se ha enviado correctamente su mensaje.')
                return redirect("TragonBall:contacto")
            except:    
                return redirect("TragonBall:contacto")
    return render(request, "contacto.html", {"miFormulario":formulario})

#Tipos de pago
def tiposPago(request):
    return render(request, 'tiposPago.html')

def carro(request):
    return render(request, "carro.html")

def comprar(request):
    return render(request, "paypal/comprar.html")

carro/views.py
from django.shortcuts import render
from .carro import Carro
from TragonBall.models import *
from django.shortcuts import redirect

# Create your views here.

def agregar_producto(request, producto_id):
    carro=Carro(request)
    producto = ProductoElaborado.objects.get(id_producto=producto_id)
    carro.agregar(producto=producto)
    return redirect('TragonBall:carro')

def eliminar_producto(request, producto_id):
    carro=Carro(request)
    producto = ProductoElaborado.objects.get(id_producto=producto_id)
    carro.eliminar(producto=producto)
    return redirect('TragonBall:carro')

def restar_producto(request, producto_id):
    carro=Carro(request)
    producto = ProductoElaborado.objects.get(id_producto=producto_id)
    carro.restar_producto(producto=producto)
    return redirect('TragonBall:carro')

def limpiar_carro(request, producto_id):
    carro=Carro(request)
    carro.limpiar_carro()
    return redirect('TragonBall:carro')

TragonBall/templates/iniciarsesion.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tragón Ball Z | Login</title>
    <link rel="icon" href="../static/img/esfera.ico">
    <!---LINK CSS-->
    <link rel="stylesheet" type="text/css" href="../static/css/bootstrap.min.css">
    <link rel="stylesheet" href="../static/css/estilo.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <script type="text/javascript" src="../static/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="../static/js/jquery-3.6.1.min.js"></script>

</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'TragonBall:inicio' %}"><img src="../static/img/brand1.png" alt="Tragón Ball Z" width="200" height="70"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'TragonBall:inicio' %}">Inicio</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Categorías
                        </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'TragonBall:producto' %}">Productos</a></li>
                        <li><a class="dropdown-item" href="{% url 'TragonBall:promocion' %}">Promociones</a></li>
                    </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'TragonBall:nosotros' %}">Nosotros</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'TragonBall:contacto' %}">Contáctanos</a>
                    </li>
                </ul>

                <!-- Icons -->
                {% if request.session.Email %}
                <div class="cont-icon ">
                <a href="{% url 'TragonBall:carro' %}" class="bi bi-cart-fill"></a> 
                </div>
                {{request.session.Email}} &nbsp; &nbsp; <a class="text-decoration-none" href="{% url 'TragonBall:cerrarSesion' %}">Cerrar sesión</a>
                {% else %}
                <div class="cont-icon">
                  <a href="{% url 'TragonBall:paginaLogin' %}" class="bi bi-person-circle m-1"></a>
                  <!--<a href="" class="bi bi-cart-fill"></a>-->
                </div>
                {% endif %}
          </div>
        </div>
    </nav>


    <section class="form-login" style=" background-image: url(../static/img/3742148.jpg); background-repeat: repeat;" >
        <form method="post">
            <div class="mas d-flex align-items-center h-100">
                <div class="container mt-5 mb-5">
                    <div class="row justify-content-center">
                        <div class="col-12 col-xl-10">
                            <div class="card">
                                <div class="card-body p-5">
                                    <div class="row d-flex align-items-center">
                                        <div class="col-md-6 col-xl-7"> 
                                            <div class="text-center pt-md-2 pb-4 my-md-1">
                                                <img src="../static/img/Dragon-Ball-Goku-PNG-Photo.png" style="height: 25%; width: 90%;" alt="">
                                            </div>                                                
                                        </div>
                                        <div class="col-md-6 col-xl-4 text-center">
                                            
                                            <img src="../static/img/Bienvenido.png" alt="">
                                            <p></p>
                                            {% csrf_token %}
                                            <div class="form-outline mb-3">
                                                <label for="correo" class="form-label">Correo electrónico</label>
                                                <input style="width: 100%;" type="text" name="correo" id="correo" placeholder="Ingrese su email" class="form.control form-control-lg" required>                                               
                                            </div>

                                            <div class="form-outline mb-4">
                                                <label for="password" class="form-label">Contraseña</label>
                                                <input style="width: 100%;" type="password" id="password" placeholder="Ingrese su contraseña" name="password"  class="form-control form-control-lg" maxlength="16" required>
                                            </div>

                                            <div class="text-center">
                                                <button class="btn btn-info btn.block btn-lg mt-1 w-100 p-2" type="submit">Iniciar Sesión</button>
                                                <br>
                                                <br>
                                                &nbsp;&nbsp;
                                                {% if messages %}
                                                {% for msg in messages %}
                                                <div class="alert alert-danger" role="alert">
                                                    <b>{{msg}}</b>
                                                </div>                   
                                                {% endfor %}
                                                {% endif %}
                                                <a href="#" class="small mt-3 mb-4 text-muted p-2 mt-3">¿Has olvidado tu contraseña?</a>
                                                <br>
                                                <br>
                                                <p class="d-inline-block">¿Aun no tienes cuenta?</p> <a href="{% url 'TragonBall:reg' %}" class="link-info">Regístrate <i class="fas fa-long-arrow-alt-right"></i></a>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>

    </section>

<footer class="pie-pagina">
    <div class="grupo1">
        <div class="box">
            <figure>
                <a href="">
                    <img style="width: 75%; margin-left: 12%;" src="../static/img/esfera.png" alt="esfera">
                </a>
            </figure>
        </div>

        <div class="box text-center">
            <h2>Contacto</h2>
            <div class="cont"></div>
            <p>Correo electrónico:</p>
            <a href="mailto:tragonballzpyme@gmail.com">tragonballzpyme@gmail.com</a>
            <p>Número de teléfono:</p>
            <a href= "tel:+56987654321">+569 8765 4321</a>
            <p>Ponte en comunicación con nosotros!</p>
        </div>

        <div class="box text-center">
            <h2>Ayuda pedidos</h2>
            <div class="ayuda">
                <a href="{% url 'TragonBall:tiposPago' %}">Tipos de pago</a>
                <p></p>
            </div>
        </div>
    </div>
    <div class="grupo-2"></div>
        <small>&copy; 2021 <b>Tragón Ball Z</b> - Todos los derechos reservados.</small>
</footer>
</body>
</html>

TragonBall/templates/simple_checkout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Integración Paypal - Django</h1>
    <div id="paypal-button-container"></div>


    <script src="https://www.paypal.com/sdk/js?client-id=AbqZrFYyXZrbYCSiffBTdEiDKEtA80zr5diV2DjN4twgVB8WuvfvfDg1S1ixAEKGiR55ft9aHjIJQzBF&currency=USD">
        // Required. Replace SB_CLIENT_ID with your sandbox client ID.
    </script>

    <script>
        paypal.Buttons({
            createOrder: function(data, actions) {
                // This function sets up the details of the transaction, including the amount and line item details.
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: '{{importe_total_carro}}'
                        }
                    }]
                });
            },
            onApprove: function(data, actions) {
                // This function captures the funds from the transaction.
                return actions.order.capture().then(function(details) {
                    // this function shows a transaction success message to your buyer.
                    alert('Transaction completed by ' + details.payer.name.given_name);
                });
            }
        }).render('#paypal-button-container');
        // This function displays Smart Payment Buttons on your web page.
    </script>
</body>
</html>